OrdererOrgs:
  - Name: Orderer
    Domain: mainorderer.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1_Publisher
    Domain: PublisherOrg.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2_CrimeChecker
    Domain: CheckerOrg.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org3_Recruiter
    Domain: RecruiterOrg.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org4_HealthChecker
    Domain: HealthCheckerOrg.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org5_Person
    Domain: PersonOrg.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
